### ISSUE TITLE
AttributeError: 'Water' object has no attribute 'direction'

### ISSUE THREAD

**Issue by marcobergman** [pypilot/pypilot#182]
Just downloaded latest pypilot from source; this seems to happen when I _stop_ feeding NMEA0183 messages to TCP/20220. 
```
Traceback (most recent call last):
  File "/usr/local/bin/pypilot", line 33, in <module>
    sys.exit(load_entry_point('pypilot==0.35', 'console_scripts', 'pypilot')())
  File "/usr/local/lib/python3.9/dist-packages/pypilot/autopilot.py", line 453, in main
    ap.iteration()
  File "/usr/local/lib/python3.9/dist-packages/pypilot/autopilot.py", line 335, in iteration
    self.sensors.poll()
  File "/usr/local/lib/python3.9/dist-packages/pypilot/sensors.py", line 349, in poll
    self.nmea.poll()
  File "/usr/local/lib/python3.9/dist-packages/pypilot/nmea.py", line 423, in poll
    self.read_process_pipe()
  File "/usr/local/lib/python3.9/dist-packages/pypilot/nmea.py", line 343, in read_process_pipe
    self.sensors.lostdevice(msgs[4:])
  File "/usr/local/lib/python3.9/dist-packages/pypilot/sensors.py", line 385, in lostdevice
    self.lostsensor(sensor)
  File "/usr/local/lib/python3.9/dist-packages/pypilot/sensors.py", line 366, in lostsensor
    sensor.reset()
  File "/usr/local/lib/python3.9/dist-packages/pypilot/sensors.py", line 320, in reset
    self.direction.set(False)
AttributeError: 'Water' object has no attribute 'direction'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/usr/local/lib/python3.9/dist-packages/pypilot/autopilot.py", line 186, in cleanup
```

**Comment by marcobergman** [comment]
Still there; this time it happens when I stop the feed to the nmea client:

```
Traceback (most recent call last):
  File "/usr/local/bin/pypilot", line 33, in <module>
server/client is running too _slowly_ 0.048332031999962055
sensor lost gps tcp GPsocket2 Mon Jan  9 14:06:39 2023
sensor lost wind tcp IIsocket2 Mon Jan  9 14:06:39 2023
sensor lost water tcp IIsocket2 Mon Jan  9 14:06:39 2023
    sys.exit(load_entry_point('pypilot==0.36', 'console_scripts', 'pypilot')())
  File "/usr/local/lib/python3.9/dist-packages/pypilot/autopilot.py", line 453, in main
    ap.iteration()
  File "/usr/local/lib/python3.9/dist-packages/pypilot/autopilot.py", line 335, in iteration
    self.sensors.poll()
  File "/usr/local/lib/python3.9/dist-packages/pypilot/sensors.py", line 361, in poll
    self.lostsensor(sensor)
  File "/usr/local/lib/python3.9/dist-packages/pypilot/sensors.py", line 366, in lostsensor
    sensor.reset()
  File "/usr/local/lib/python3.9/dist-packages/pypilot/sensors.py", line 320, in reset
    self.direction.set(False)
AttributeError: 'Water' object has no attribute 'direction'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/usr/local/lib/python3.9/dist-packages/pypilot/autopilot.py", line 186, in cleanup
    raise KeyboardInterrupt # to get backtrace on all processes
KeyboardInterrupt
closing autopilot
```

**Comment by stelian42** [comment]
At the moment Water sensor support is incomplete and under development. You can fix this issue probably by just removing line 320 from sensors.py:
         self.direction.set(False)

**Comment by marcobergman** [comment]
Thx. If it is under development, it should not break the master. Currently pypilot crashes each time a nmea source is disconnected, including the regular feed to the 20220 socket.

**Comment by seandepagnier** [comment]
Thanks for reporting this, and agreed master should not throw exceptions.

I pushed a small change which will hopefully fix this.

**Comment by marcobergman** [comment]
I'm afraid I can still crash it. You changed line 321, the error sits in line 320. Removing the line 320 does do the trick:

@@ -317,7 +317,7 @@ class Water(Sensor):
     def reset(self):
-        self.direction.set(False)
+        #self.direction.set(False)
         self.leeway.set(False)
